# Change prefix
set-option -g prefix C-a
unbind C-b
bind C-a send-prefix

# shortcut for reloading config
bind r source-file "~/.tmux.conf" \; display-message "Config reloaded."

# Index shall start at 1, not 0
set-option -g base-index 1
set-option -g pane-base-index 1

# vim mode
setw -g mode-keys vi

# Reorder all windows
# bind ß move-window -r

# enable mouse
set-option -g mouse on

# scrollback buffer
set-option -g history-limit 10000

# window title
set-option -g set-titles on
set-option -g set-titles-string "#T"

# which dir is shell on new panes / windows
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind '%' split-window -h -c "#{pane_current_path}"

# pass events down to tmux
set-option -s focus-events on

# zero escape time
set-option -s escape-time 0

# truecolor with alacritty
set -as terminal-features ",alacritty*:RGB"

##        ##
# Styling #
##        ##

rarrow=''
larrow=''
session_icon=''

MOON=#00abab
FOREST=#a7c080
G0=#262626
G1=#303030
G2=#3a3a3a
G3=#444444
G4=#626262

TC=${MOON}

prefix_highlight_pos='R' # or LR

set -g status-position bottom

set -g status-bg "$G0"
set -g status-fg "$G4"

# set -g @prefix_highlight_show_copy_mode 'on'
# set -g @prefix_highlight_copy_mode_attr "fg=$TC,bg=$G0,bold"
# set -g @prefix_highlight_output_prefix "#[fg=$TC]#[bg=$G0]$larrow#[bg=$TC]#[fg=$G0]"
# set -g @prefix_highlight_output_suffix "#[fg=$TC]#[bg=$G0]$rarrow"

## We will config the left side now

# show hostname & session
LS="#[fg=$G0,bg=$TC,bold] #h#[fg=$TC,bg=$G0,nobold]${rarrow}#[fg=$TC,bg=$G0] ${session_icon} #S "

# prefix highlight on left side
# LS="$LS#{prefix_highlight}"

set -g status-left-length 100
set -g status-left ${LS}

# remove right side
set -g status-right ""

# Window status format
set -g window-status-format         "#[fg=$G0,bg=$G2]$rarrow#[fg=$TC,bg=$G2] #I #W #[fg=$G2,bg=$G0]$rarrow"
set -g window-status-current-format "#[fg=$G0,bg=$TC]$rarrow#[fg=$G0,bg=$TC,bold] #I #W #[fg=$TC,bg=$G0,nobold]$rarrow"

# Window status style
# set -g window-status-style          "fg=$TC,bg=$G0,none"
# set -g window-status-last-style     "fg=$TC,bg=$G0,bold"
# set -g window-status-activity-style "fg=$TC,bg=$G0,bold"

# Window separator
set -g window-status-separator ""

# Pane border
# set -g pane-border-style "fg=$G3,bg=default"

# Active pane border
# set -g pane-active-border-style "fg=$TC,bg=default"

# Pane number indicator
set -g display-panes-colour "$G3"
set -g display-panes-active-colour "$TC"
