#!/bin/sh

# Example for $XDG_CONFIG_HOME/nsxiv/exec/image-info
# Called by nsxiv(1) whenever an image gets loaded.
# The output is displayed in nsxiv's status bar.
# Arguments:
#   $1: path to image file (as provided by the user)
#   $2: image width
#   $3: image height
#   $4: fully resolved path to the image file

s="     " # field separator

exec 2>/dev/null

filename=$(basename -- "$1")
filesize=$(du -Hh -- "$1" | cut -f 1)
geometry="${2}x${3}"

IFS=',' read -r -a array <<< $(exiftool -model -CreateDate -api geolocation "-geolocationcity" "-geolocationcountry" -csv "$1" | tail -1)
model="${array[1]}"
createdate="${array[2]}"
city="${array[3]}"
country="${array[4]}"

echo "${filesize}${s}${geometry}${s}${filename}${s}${createdate}${s}${city} - ${country}${s}${model}"

